services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - django-backend
    env_file:
      - ./client/.env
    networks:
      - rag-network

  django-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - pgvector
    networks:
      - rag-network

  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rag-network

volumes:
  pgdata:

networks:
  rag-network:
    driver: bridge
