# Generated by Django 5.1.5 on 2025-01-19 14:07

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        # Add your app's previous migration here if any
        # For now if you are doing it first-time without previous migration then no need to worry !
        # Just keep it blank
    ]

    operations = [
        VectorExtension(),
    ]
