# Generated by Django 5.1.5 on 2025-01-19 23:54

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInformationChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                'db_table': 'document_information_chunks',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='rag_app.documents')),
            ],
            options={
                'db_table': 'document_tags',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
        migrations.AddField(
            model_name='documentinformationchunks',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_information_chunks', to='rag_app.documents'),
        ),
        migrations.AddField(
            model_name='documenttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='rag_app.tags'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX embedding_vector_cosine_ops 
            ON document_information_chunks 
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists=100);
            """,
            reverse_sql="DROP INDEX IF EXISTS embedding_vector_cosine_ops;"
        ),
        migrations.RunSQL(
            sql="ANALYZE document_information_chunks;",
            reverse_sql=""
        ),
    ]
