# Generated by Django 5.1.5 on 2025-01-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_documentinformationchunks_documents_documenttags_and_more'),
    ]

    operations = [
        
    ]
