# Generated by Django 5.1.5 on 2025-01-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_documentinformationchunks_embedding_vector_cosine_ops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='name',
        ),
        migrations.AddField(
            model_name='documents',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
