# Generated by Django 5.1.5 on 2025-01-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0005_remove_documents_name_documents_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinformationchunks',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
