# Generated by Django 5.1.5 on 2025-01-20 11:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0007_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='refrences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
